language: node_js
node_js: node
stages:
  - quality
  - test
  - build
jobs:
  include:
    - stage: quality
      name: lint
      script: yarn lint
    - name: prettier
      script: yarn prettier
    - stage: test
      name: jest
      script: yarn test
    - stage: build
      script: yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./build
  on:
    branch: master
